# -*- coding: utf-8 -*-
"""LVADSUSR126-Tushar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXQskHKIGOi83PbimCRQSkBF09efNqk4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1
data = pd.read_excel("/content/Walmart_Dataset Python_Final_Assessment.xlsx")
df=pd.DataFrame(data)
df.head(3)

#1
print(df.shape)

#1
print(df.dtypes)

#1
df.describe().loc[['25%', '50%', '75%']]

#2
df.isna().sum()
df.dropna(inplace=True)
df.isna().sum()

#2
df.drop_duplicates(inplace=True)
print(df.shape)

#3
print(df.mean())
print(df.median())
print(df.mode())
print(df.std())
print(df.var())

#3
print(df.median())

#3
print(df.mode())

#3
print(df.var())

#3
print(df.std())

#4
plt.bar(df['Quantity'],df['Sales'])
plt.xlabel('Quantity')
plt.ylabel('Sales')
plt.title('Sales vs Quantity')

#4
sns.scatterplot(data=df,x='Quantity',y='Sales')

#4
j=df.groupby('Category')['Sales'].sum()
b=pd.DataFrame(j)
sns.barplot(data=b,x='Category',y='Sales')

df.set_index('Category')
sns.lineplot(x='Category',y='Profit',marker='o',label='revenue',data=df)
sns.lineplot(x='Category',y='Sales',marker='o',label='profit',data=df)
plt.grid()
plt.tight_layout()
plt.show()

#5
sales_quantity_corr=df['Sales'].corr(df['Quantity'])
sales_profit_corr=df['Sales'].corr(df['Profit'])
profit_quantity_corr=df['Profit'].corr(df['Quantity'])
print(sales_quantity_corr)
print(sales_profit_corr)
print(profit_quantity_corr)

#5
print(df.corr())

#5
h=df.corr()
sns.heatmap(h, annot=True,fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

#6
sns.boxplot(data=df)
plt.title("Outlier")
plt.show()
#From the above graph it can be seen that there is a single outier in profit and 2 outliers in sales

#6
plt.scatter(df['Quantity'], df['Sales'])
plt.title("Scatter Plot for Outlier detection")
plt.xlabel('Sales')
plt.ylabel('Quantity')
plt.show()

#7 Trend Analysis
#1
sns.lineplot(x="Order Date",y="Profit",marker='o',label="Profit",data=df)
sns.lineplot(x="Order Date",y="Sales",marker='o',label="Sales",data=df)
plt.legend()
plt.show()

#7 Trend Analysis
#2
sns.lineplot(x="Order Date",y="Category",marker='o',label="Profit",data=df)
plt.legend()
plt.show()

#7 Customer Analysis
#1
a=df.groupby(df['EmailID']).count()
b=a.sort_values('Sales',ascending=False)
c=pd.DataFrame(b)
c.head(5)

#7 Customer Analysis
a=df.groupby(df['Product Category']).sum()
c=pd.DataFrame(b)

"""7 Comprehensive Analysis

1.

To optimize the supply chain based on insights from sales velocity and order fulfillment data, several strategies can be implemented.by analyzing sales velocity data, businesses can forecast demand more accurately, allowing for better inventory management and reducing excess stock. insights from order fulfillment data can help identify bottlenecks or inefficiencies in the supply chain, enabling improvements in delivery times and customer satisfaction. Additionally, implementing lean inventory practices and adopting technology such as automation and data analytics can streamline operations and reduce costs. Furthermore, fostering collaboration and communication among supply chain partners can lead to smoother coordination and faster response to changes in demand. Lastly, continuously monitoring key performance indicators (KPIs) and adapting strategies based on real-time data can ensure agility and resilience in the supply chain.

7 Comprehensive Analysis

2.

Sales can be distributed according to the geography as there is a need for goods or products based on their geographic place as well. each customer or salesperson performs sales according to geographic area only

7. comprehensive analysis

3.

Yes, we can identify patterns and make predictions about high-value customers using various data analysis and machine learning techniques. By analyzing historical customer data, such as purchase history, frequency of purchases, average order value, and customer demographics, we can identify patterns that distinguish high-value customers from others. Additionally, predictive modeling techniques such as regression analysis, decision trees, or clustering algorithms can be employed to forecast future customer behavior and identify potential high-value customers.
"""